<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>TelegramNotifier</PackageId>
    <Version>2.0.0</Version>
    <Authors>Anushervon</Authors>
    <Description>Simple Telegram notifier for sending exceptions and logs</Description>
    <PackageTags>telegram;logging;exceptions;notifier</PackageTags>
    <RepositoryUrl>https://github.com/bekov0004/TelegramNotifier</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>See full changelog: https://github.com/bekov0004/TelegramNotifier/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />

    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
